services:
  - type: web
    name: nail-try-on
    runtime: docker
    plan: free
    envVars:
      - key: ROBOFLOW_API_KEY
        sync: false
      - key: NAIL_ALPHA
        value: 0.4
      - key: MAX_PROCESS_FPS
        value: 10
      - key: FRAME_SKIPPED_BLUR_THRESHOLD
        value: 30.0
      - key: MAX_CAPTURE_DIM
        value: 1280
      - key: MAX_SEND_FPS
        value: 10
